num_actions: 29
num_dofs: 29
history_length: 10
action_scale: 0.25
ball_obs_dim: 3
include_base_ang_vel: true
include_projected_gravity: true
g1_default_joint_angles:
- -0.1
- 0.2
- 0.0
- 0.3
- -0.2
- -0.2
- -0.1
- -0.2
- 0.0
- 0.3
- -0.2
- 0.2
- 0.0
- 0.0
- 0.0
- 0.0
- 0.5
- 0.0
- 1.2
- 0.0
- 0.0
- 0.0
- 0.0
- -0.5
- 0.0
- 1.2
- 0.0
- 0.0
- 0.0
t2_default_joint_angles:
- 0.0
- 0.0
- 0.0
- 0.5
- 1.2
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- -0.5
- 1.2
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- -0.1
- 0.2
- 0.0
- 0.3
- -0.2
- -0.2
- -0.1
- -0.2
- 0.0
- 0.3
- -0.2
- 0.2
